baseurl = "https://naplo.github.io"  #github pages ç½‘å€ï¼Œåç»­éƒ¨ç½²æ—¶ä¿®æ”¹
defaultContentLanguage = "zh"  #ç½‘ç«™è¯­è¨€å›½é™…åŒ–é€‰é¡¹
languageCode = "zh"  #æ–‡ç« ç¼–ç è¯­è¨€å›½é™…åŒ–é€‰å‹
title = "Shoumin'Blog"  #ç½‘ç«™æ ‡é¢˜
theme = "hugo-theme-dream"  #hugoä¸»é¢˜åï¼Œæ­¤å¤„éœ€ä¸themesæ–‡ä»¶å¤¹ä¸‹çš„ä¸»é¢˜æ–‡ä»¶å¤¹åç§°ä¸€è‡´

# [services]
# [services.disqus]
# shortname = ""
# [services.googleAnalytics]
# ID = ""

[params]
# zenMode = true

lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = "img/background/global-background.jpg"
# backgroundImageDark = "img/background/road.jpg"

author = "shoumin"  #ç½‘ç«™ä½œè€…
description = "shouminçš„ä¸ªäººåšå®¢"  #ç½‘ç«™æè¿°
avatar = "img/avatar/corgi.png"  #ä¸ªäººå¤´åƒï¼Œå¤´åƒæ–‡ä»¶æ”¾åˆ°static/img/avatar/ä¸‹ï¼Œæ–‡ä»¶åä¿æŒéœ€ä¸€è‡´
headerTitle = "Shoumin'Blog"  #é¦–é¡µæ ‡é¢˜
motto = "ä¿®å¾·åšå­¦ èº¬è¡Œè·µå±¥"  #é¦–é¡µæ ¼è¨€

# é¡µè„š
# footerBottomText = "ğŸ¦´ Powered by Hugo with theme Dream."
footerBottomText = 'ğŸ¦´ Powered by <a href="https://gohugo.io/">Hugo</a> with theme <a href="https://github.com/g1eny0ung/hugo-theme-dream">Dream</a>.'

# rss = true

# utterancesRepo = ""

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""r

# waline = true
# walineServer = ""

# email = ""

siteStartYear = 2025  #ç½‘ç«™å¼€å§‹å¹´ä»½

favicon = "favicon.ico"  #ç½‘ç«™å›¾æ ‡ï¼Œå›¾æ ‡æ–‡ä»¶æ”¾åˆ°static/img/è·¯å¾„ä¸‹

# favicon = '<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%2210 0 100 100%22><text y=%22.90em%22 font-size=%2290%22>ğŸ¦´</text></svg>"></link>'



# Syntax highlighting
# customSyntaxHighlighting = true

# options
stickyNav = true
# reorderNavItems = ["about", "search", "rss", "posts", "categories", "tags"]
collapseNavItems = ["posts", "categories", "tags"]  #æŠ˜å å¯¼èˆªé€‰å‹
noDefaultSummaryCover = true
showTableOfContents = true
showSummaryCoverInPost = true  #æ˜¾ç¤ºæ–‡å­—å¤´å›¾
imageZoomableInPost = true
showPrevNextPost = true
# reorderShares = ["x", "facebook", "whatsapp"]
reorderShares = [""]  #é‡ç½®æ–‡ç« é‡Œçš„åˆ†äº«æŒ‰é’®

# [params.navItems]

# [params.twikoo]
# enabled = true
# envID = ""
# region = ""
# lang = ""

# [params.advanced]
# customCSS = ["css/custom.css"]
# customJS = []

[params.experimental]
jsDate = true
jsDateFormat = "yyyyå¹´MMæœˆddæ—¥"  #ç½‘ç«™æ—¥æœŸæ˜¾ç¤ºæ ¼å¼

[params.assets]
disableFingerprinting = true  #æ·»åŠ è¿™ä¸¤è¡Œè§£å†³éƒ¨ç½²åˆ°GitHub Pagesä¸Šcsså¤±æ•ˆé—®é¢˜